In [3]:
import numpy as np

In [4]:
np.random.seed(seed=1234)

In [9]:
x = np.array(6)
print("x : ", x)  # Because it's a scalar
print("X ndim : ", x.ndim)
print("X shape : ", x.shape)
print("X datatype : ", x.dtype)
print("X size : ", x.size)
print("\n")
x = np.array([1, 2, 3])
print("x : ", x)  # Because it's a 1D array
print("X ndim : ", x.ndim)
print("X shape : ", x.shape)
print("X datatype : ", x.dtype)
print("X size : ", x.size)

x :  6
X ndim :  0
X shape :  ()
X datatype :  int64
X size :  1


x :  [1 2 3]
X ndim :  1
X shape :  (3,)
X datatype :  int64
X size :  3


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x : ", x)  # Because it's a scalar
print("X ndim : ", x.ndim)
print("X shape : ", x.shape)
print("X datatype : ", x.dtype)
print("X size : ", x.size)

x :  [[1 2 3]
 [4 5 6]]
X ndim :  2
X shape :  (2, 3)
X datatype :  int64
X size :  6


In [12]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


In [13]:
print("np.zeros((2,2)):\n", np.zeros((2, 2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]


In [23]:
print("np.zeros((3)):\n", np.zeros((3)))
print("np.ones((2,2))\n", np.ones((2, 2)))
print("np.eyes((2))\n", np.eye((2)))
print("np.random.random((2,2)):\n", np.random.random((2, 2)))

np.zeros((3)):
 [0. 0. 0.]
np.ones((2,2))
 [[1. 1.]
 [1. 1.]]
np.eyes((2))
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [24]:
x = np.array([1, 2, 3])
print("x: ", x)
print("x[0]: ", x[0])
x[0] = 0
print("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [27]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)
print("x column 1: ", x[:, 1])
print("x row 0: ", x[0, :])
print("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [28]:
print(x)
rows_to_get = np.array([0, 1, 2])
print("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print("cols_to_get: ", cols_to_get)
print("indexed values: ", x[rows_to_get, cols_to_get])  # (0,0) (1,2) (2,1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [30]:
# Boolean array indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
print("x:\n", x)
print("x > 2:\n", x > 2)
print("x[x > 2]:\n", x[x > 2].reshape(2, 2))


x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [[3 4]
 [5 6]]


In [31]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[1, 2], [3, 4]], dtype=np.float64)
print("x + y:\n", np.add(x, y))  # or x + y
print("x - y:\n", np.subtract(x, y))  # or x - y
print("x * y:\n", np.multiply(x, y))  # or x * y, this is not dot product

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


In [33]:
print("Dot product of X and Y : ", x.dot(y))

Dot product of X and Y :  [[ 7. 10.]
 [15. 22.]]


In [41]:
x = np.array([[1, 2], [3, 4]])
print(x)
print("sum all : ", np.sum(x))
print("sum along axis 0 : ", np.sum(x, axis=0))
print("sum along axis 1 : ", np.sum(x, axis=1))

[[1 2]
 [3 4]]
sum all :  10
sum along axis 0 :  [4 6]
sum along axis 1 :  [3 7]


In [42]:
print("min : {} and max : {}".format(np.min(x), np.max(x)))

min : 1 and max : 4


In [43]:
x = np.array([[1, 2], [3, 4]])
y = np.array(3)
z = x + y
print("z:\n", z)

z:
 [[4 5]
 [6 7]]


In [47]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b

In [48]:
a.shape
b.shape
c.shape
print(c)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [49]:
a = a.reshape(-1, 1)
a.shape
c = a + b
c.shape
print(c)

[[ 6]
 [ 8]
 [10]]


In [60]:
x = np.array([1, 2, 3, 4, 5, 6])
x = x.reshape(6, -1)
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [70]:
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
              [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print("x:\n", x)
print("x.shape: ", x.shape)
y = np.transpose(x, (1, 0, 2))
print("y:\n", y)
print("y.shape: ", y.shape)
z_correct = np.reshape(y, (y.shape[0], -1))
print("z_correct:\n", z_correct)
print("z_correct.shape: ", z_correct.shapḛ)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)
y:
 [[[ 1  1  1  1]
  [10 10 10 10]]

 [[ 2  2  2  2]
  [20 20 20 20]]

 [[ 3  3  3  3]
  [30 30 30 30]]]
y.shape:  (3, 2, 4)
z_correct:
 [[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
z_correct.shape:  (3, 8)


In [71]:
x = np.random.random((2, 3))
print(x)
print(x.shape)
y = np.concatenate([x,x] , axis = 0)
print(y)
print(y.shape)

[[0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263]]
(2, 3)
[[0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263]
 [0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263]]
(4, 3)


In [72]:
x = np.random.random((2, 3))
print(x)
print(x.shape)
y = np.concatenate([x,x] , axis = 1)
print(y)
print(y.shape)

[[0.35781727 0.50099513 0.68346294]
 [0.71270203 0.37025075 0.56119619]]
(2, 3)
[[0.35781727 0.50099513 0.68346294 0.35781727 0.50099513 0.68346294]
 [0.71270203 0.37025075 0.56119619 0.71270203 0.37025075 0.56119619]]
(2, 6)


In [100]:
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
              [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print(x)
print(y)

[[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
[[[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]


In [101]:
x,y = np.vsplit(x,2)
print(x)
print(y)

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]]
[[[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]


In [103]:
x = np.concatenate([2 ,x,y] , axis = 0)
print(x)

ValueError: zero-dimensional arrays cannot be concatenated